# Generated by Django 5.2.4 on 2026-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('مخدوم', 'مخدوم'), ('خادم عادي', 'خادم عادي'), ('امين مساعد اسرة', 'امين مساعد اسره'), ('امين اسرة', 'امين اسرة'), ('امين مرحلة', 'امين مرحلة'), ('امين الشمامسة', 'امين الشمامسة')], default='مخدوم'),
        ),
    ]
