# Generated by Django 5.2.4 on 2025-08-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=50)),
                ('year_of_entrance', models.DateField()),
                ('year_of_graduation', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stages.family')),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('امين مرحلة', 'امين مرحلة'), ('امين اسرة', 'امين اسرة'), ('امين مساعد اسرة', 'امين مساعد اسره'), ('امين الشمامسة', 'امين الشمامسة'), ('خادم عادي', 'خادم عادي')], default='خادم عادي', max_length=50)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servants', to='stages.family')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servants', to='stages.stage')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='stages.stage'),
        ),
    ]
