# Generated by Django 5.2.4 on 2026-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=50)),
                ('year_of_entrance', models.DateField()),
                ('year_of_graduation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('امين مساعد اسرة', 'امين مساعد اسره'), ('امين الشمامسة', 'امين الشمامسة'), ('امين اسرة', 'امين اسرة'), ('خادم عادي', 'خادم عادي'), ('امين مرحلة', 'امين مرحلة')], default='خادم عادي', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
