# Generated by Django 5.2.4 on 2025-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='role',
            field=models.CharField(choices=[('امين مساعد اسرة', 'امين مساعد اسره'), ('خادم عادي', 'خادم عادي'), ('امين اسرة', 'امين اسرة'), ('امين الشمامسة', 'امين الشمامسة'), ('امين مرحلة', 'امين مرحلة')], default='خادم عادي', max_length=50),
        ),
    ]
