# Generated by Django 5.2.4 on 2025-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_servant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='role',
            field=models.CharField(choices=[('امين مرحلة', 'امين مرحلة'), ('خادم عادي', 'خادم عادي'), ('امين مساعد اسرة', 'امين مساعد اسره'), ('امين الشمامسة', 'امين الشمامسة'), ('امين اسرة', 'امين اسرة')], default='خادم عادي', max_length=50),
        ),
    ]
