# Generated by Django 5.2.4 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
