# Generated by Django 5.2.4 on 2025-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_alter_servant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='role',
            field=models.CharField(choices=[('امين اسرة', 'امين اسرة'), ('امين الشمامسة', 'امين الشمامسة'), ('امين مرحلة', 'امين مرحلة'), ('امين مساعد اسرة', 'امين مساعد اسره'), ('خادم عادي', 'خادم عادي')], default='خادم عادي', max_length=50),
        ),
    ]
