# Generated by Django 5.2.4 on 2025-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_servant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='role',
            field=models.CharField(choices=[('امين مساعد اسرة', 'امين مساعد اسره'), ('امين اسرة', 'امين اسرة'), ('خادم عادي', 'خادم عادي'), ('امين مرحلة', 'امين مرحلة'), ('امين الشمامسة', 'امين الشمامسة')], default='خادم عادي', max_length=50),
        ),
    ]
