# Generated by Django 5.2.4 on 2026-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('unblock', 'Unblock'), ('block', 'Block'), ('login', 'Login'), ('other', 'Other')], max_length=30),
        ),
    ]
